### PR TITLE
added file structure for iceland directory

### PR DESCRIPTION
**Pull request by morriscodez**
```
git fetch --all
git checkout dm-iceland-files
tree
```

### CODE REVIEW

**Review by SubtleCo — COMMENTED** [review]
Maybe we should uncapitalize the directories containing each .js file

**Review by SubtleCo — APPROVED** [review]
LOVE that lowercase

**Review by peytonkemp — APPROVED** [review]
capitalizations are fun

**Review by calebsjames — APPROVED** [review]
Great

**Pull request merged**
