### PR TITLE
Created HTML for countryContainer, countryContainer__Details, and cou…

### PR DESCRIPTION
**Pull request by morriscodez**
Added HTML for 
```
countryContainer
  countryContainer__header
  countryContainer__details
    countryContainer__cities
       cityCard
          img
          name
```

### CODE REVIEW

**Review by calebsjames — APPROVED** [review]
I see all our discussed elements. Spelling and syntax all look good.

**Review by SubtleCo — APPROVED** [review]
That'll do nicely, thanks!

**Review by SubtleCo — CHANGES_REQUESTED** [review]
Actually, one change - remember that the class "countryContainer__header" isn't actually a header - the logo/nav bar at the top is the actual header. Maybe we should change the class name to "countryCountainer__top" or something to make it less confusing

**Comment by calebsjames** [comment]
> Actually, one change - remember that the class "countryContainer__header" isn't actually a header - the logo/nav bar at the top is the actual header. Maybe we should change the class name to "countryCountainer__top" or something to make it less confusing

It actually overlaps with Alex's code that is also waiting for approval:

```
<div class="countryContainer">
            <section class="countryContainer__header">
                <img class="countryContainer__img" src="" alt="">
                <h2 class="countryContainer__countryName"></h2>
            </section>

```
I think using the` <section>` tag is maybe better. as opped to what's here which is:

```
<div class="countryContainer">
    <header class="countryContainer_header">
        <img src="" alt="" class="countryContainer__img">
        <h2 class="countryContainer__countryName"></h2>
    </header>
```

I don't mind it being called countryContainer__header as it's very specific to what it's header to but I don't know that we should use the `header` semantic.

**Review by SubtleCo — APPROVED** [review]
LOVE it

**Review by peytonkemp — APPROVED** [review]

**Comment by morriscodez** [comment]
Merging approved changes for countryContainer html section

**Pull request merged**
