### PR TITLE
HTML files combined into mexico

### PR DESCRIPTION
**Pull request by calebsjames**
git fetch --all
git checkout cj-mexicoHTML
serve

Combined all HTML elements into one file. Please double check.

### CODE REVIEW

**Review by SubtleCo — APPROVED** [review]
nice

**Review by peytonkemp — APPROVED** [review]
looks great Caleb

**Review by morriscodez — APPROVED** [review]
Me gusta

**Review by SubtleCo — APPROVED** [review]
Still good!

**Pull request merged**
