### PR TITLE
corrected formatting issues with mexico landmarks.js

### PR DESCRIPTION
**Pull request by peytonkemp**

### CODE REVIEW

**Review by morriscodez — DISMISSED** [review]
good changes

**Review by SubtleCo — CHANGES_REQUESTED** [review]
I miss the landmarks title!

**Review by morriscodez — DISMISSED** [review]
slammin

**Review by SubtleCo — DISMISSED** [review]
chefkiss

**Review by SubtleCo — APPROVED** [review]
done nailed it

**Review by morriscodez — APPROVED** [review]

**Pull request merged**
