### PR TITLE
CSS components added to header.css

### PR DESCRIPTION
**Pull request by calebsjames**
**Instructions to test:**
git fetch --all
git checkout cj-cssHeaderUpdate
serve

Added basic components to header.css

### CODE REVIEW

**Review by SubtleCo — COMMENTED** [review]
dig, dag, dug ✅

**Review by morriscodez — APPROVED** [review]
Nice

**Review by SubtleCo — APPROVED** [review]
✅

**Review by peytonkemp — APPROVED** [review]
fantastic

**Pull request merged**
