### PR TITLE
Initial Commit - Boiler Plate files

### PR DESCRIPTION
**Pull request by SubtleCo**
Created initial files:

index.html
germany.html
mexico.html
iceland.html
/styles
  -main.css
  -germany.css
  -mexico.css
  -iceland.css
/scripts
  -main.js

```
git fetch --all
git checkout ram-boilerplate-files
serve
```

Note: You shouldn't see anything, all the files are blank. Please just double check my work and import statements in main.css!

### CODE REVIEW

**Review by calebsjames — APPROVED** [review]
Crushing it

**Review by morriscodez — APPROVED** [review]
I pretended to look at them while approving

**Comment by peytonkemp** [comment]
amazing!

**Review by peytonkemp — APPROVED** [review]
fantastic!

**Pull request merged**
