### PR TITLE
Automated Nav Bar, missing current page highlight

### PR DESCRIPTION
**Pull request by SubtleCo**
Automated nav bar: 
+ added scripts/main.js to each page HTML

- removed hard coded nav bar from all HTML pages

issue: currently we lost the "highlight the current page on navbar" feature

### CODE REVIEW

**Review by calebsjames — DISMISSED** [review]
That is some sexy automation

**Review by peytonkemp — DISMISSED** [review]
I'm so impressed!

**Review by calebsjames — APPROVED** [review]
B-E-A-Utifal highlighting

**Review by peytonkemp — APPROVED** [review]
Impressed yet again!

**Pull request merged**
